### PR TITLE
fix roformer models run on cuda

### PR DESCRIPTION
**Pull request by young01ai**
Hope it's helpful... I test it under:
OS: both Ubuntu 20.04 and MacOS (M2)
Python: 3.10.14
PyTorch: 2.3.1+cu118

### CODE REVIEW

**Comment by beveradb** [comment]
Thanks for raising the PR! 

However, how did you test on your M2 mac exactly?

When I tested it locally on my macbook (M3) I get the tensor device mismatch error:

```
python-audio-separator git:(fix-cuda) audio-separator -d -m model_bs_roformer_ep_317_sdr_12.9755.yaml tracks/prettier.mp3
2024-07-03 01:26:53.662 - INFO - cli - Separator version 0.17.5 beginning with input file: tracks/prettier.mp3
2024-07-03 01:26:53.662 - INFO - separator - Separator version 0.17.5 instantiating with output_dir: None, output_format: FLAC
2024-07-03 01:26:53.662 - INFO - separator - Output directory not specified. Using current working directory.
2024-07-03 01:26:53.662 - INFO - separator - Operating System: Darwin Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
2024-07-03 01:26:53.670 - INFO - separator - System: Darwin Node: MacBook-Pro-2.local Release: 23.5.0 Machine: arm64 Proc: arm
2024-07-03 01:26:53.670 - INFO - separator - Python Version: 3.11.7
2024-07-03 01:26:53.670 - INFO - separator - PyTorch Version: 2.3.0
2024-07-03 01:26:53.705 - INFO - separator - FFmpeg installed: ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
2024-07-03 01:26:53.706 - DEBUG - separator - Python package: onnxruntime-gpu not installed
2024-07-03 01:26:53.706 - DEBUG - separator - Python package: onnxruntime-silicon not installed
2024-07-03 01:26:53.706 - INFO - separator - ONNX Runtime CPU package installed with version: 1.18.0
2024-07-03 01:26:53.713 - INFO - separator - Apple Silicon MPS/CoreML is available in Torch, setting Torch device to MPS
2024-07-03 01:26:53.713 - INFO - separator - ONNXruntime has CoreMLExecutionProvider available, enabling acceleration
2024-07-03 01:26:53.713 - INFO - separator - Loading model model_bs_roformer_ep_317_sdr_12.9755.yaml...
2024-07-03 01:26:53.713 - DEBUG - separator - File already exists at /tmp/audio-separator-models/download_checks.json, skipping download
2024-07-03 01:26:53.713 - DEBUG - separator - Model download list loaded
2024-07-03 01:26:53.713 - DEBUG - separator - Searching for model_filename model_bs_roformer_ep_317_sdr_12.9755.yaml in supported_model_files_grouped
2024-07-03 01:26:53.713 - DEBUG - separator - Found input filename model_bs_roformer_ep_317_sdr_12.9755.yaml in multi-file model: Roformer Model: BS-Roformer-Viperx-1297
2024-07-03 01:26:53.713 - DEBUG - separator - Multi-file model identified: Roformer Model: BS-Roformer-Viperx-1297, iterating through files to download
2024-07-03 01:26:53.713 - DEBUG - separator - Attempting to identify download URL for config pair: model_bs_roformer_ep_317_sdr_12.9755.ckpt -> model_bs_roformer_ep_317_sdr_12.9755.yaml
2024-07-03 01:26:53.713 - DEBUG - separator - File already exists at /tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.ckpt, skipping download
2024-07-03 01:26:53.713 - WARNING - separator - The model name you've specified, model_bs_roformer_ep_317_sdr_12.9755.yaml is actually a model config file, not a model file itself.
2024-07-03 01:26:53.713 - WARNING - separator - We found a model matching this config file: model_bs_roformer_ep_317_sdr_12.9755.ckpt so we'll use that model file for this run.
2024-07-03 01:26:53.713 - WARNING - separator - To prevent confusing / inconsistent behaviour in future, specify an actual model filename instead.
2024-07-03 01:26:53.713 - DEBUG - separator - File already exists at /tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.yaml, skipping download
2024-07-03 01:26:53.714 - DEBUG - separator - All files downloaded for model Roformer Model: BS-Roformer-Viperx-1297, returning initial path /tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.ckpt
2024-07-03 01:26:53.714 - DEBUG - separator - Model downloaded, friendly name: Roformer Model: BS-Roformer-Viperx-1297, model_path: /tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.ckpt
2024-07-03 01:26:53.714 - DEBUG - separator - Loading model data from YAML at path /tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.yaml
2024-07-03 01:26:53.716 - DEBUG - separator - Model data loaded from YAML file: {'audio': {'chunk_size': 352800, 'dim_f': 1024, 'dim_t': 801, 'hop_length': 441, 'n_fft': 2048, 'num_channels': 2, 'sample_rate': 44100, 'min_mean_abs': 0.001}, 'model': {'dim': 512, 'depth': 12, 'stereo': True, 'num_stems': 1, 'time_transformer_depth': 1, 'freq_transformer_depth': 1, 'freqs_per_bands': (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 12, 12, 12, 12, 12, 12, 12, 24, 24, 24, 24, 24, 24, 24, 24, 48, 48, 48, 48, 48, 48, 48, 48, 128, 129), 'dim_head': 64, 'heads': 8, 'attn_dropout': 0.1, 'ff_dropout': 0.1, 'flash_attn': True, 'dim_freqs_in': 1025, 'stft_n_fft': 2048, 'stft_hop_length': 441, 'stft_win_length': 2048, 'stft_normalized': False, 'mask_estimator_depth': 2, 'multi_stft_resolution_loss_weight': 1.0, 'multi_stft_resolutions_window_sizes': (4096, 2048, 1024, 512, 256), 'multi_stft_hop_size': 147, 'multi_stft_normalized': False}, 'training': {'batch_size': 16, 'gradient_accumulation_steps': 1, 'grad_clip': 0, 'instruments': ['Vocals', 'Instrumental'], 'lr': 5e-05, 'patience': 2, 'reduce_factor': 0.95, 'target_instrument': 'Vocals', 'num_epochs': 1000, 'num_steps': 1000, 'augmentation': False, 'augmentation_type': 'simple1', 'use_mp3_compress': False, 'augmentation_mix': True, 'augmentation_loudness': True, 'augmentation_loudness_type': 1, 'augmentation_loudness_min': 0.5, 'augmentation_loudness_max': 1.5, 'q': 0.95, 'coarse_loss_clip': True, 'ema_momentum': 0.999, 'optimizer': 'adam', 'other_fix': False, 'use_amp': True}, 'inference': {'batch_size': 1, 'dim_t': 801, 'num_overlap': 4}}
2024-07-03 01:26:53.717 - DEBUG - separator - Importing module for model type MDXC: mdxc_separator.MDXCSeparator
2024-07-03 01:26:54.576 - DEBUG - separator - Instantiating separator class for model type MDXC: <class 'audio_separator.separator.architectures.mdxc_separator.MDXCSeparator'>
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: model_name=model_bs_roformer_ep_317_sdr_12, model_path=/tmp/audio-separator-models/model_bs_roformer_ep_317_sdr_12.9755.ckpt
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: output_dir=/Users/andrew/Projects/python-audio-separator, output_format=FLAC
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: normalization_threshold=0.9
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: enable_denoise=None, output_single_stem=None
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: invert_using_spec=False, sample_rate=44100
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: primary_stem_name=Vocals, secondary_stem_name=Instrumental
2024-07-03 01:26:54.576 - DEBUG - common_separator - Common params: is_karaoke=False, is_bv_model=False, bv_model_rebalance=0
2024-07-03 01:26:54.576 - DEBUG - mdxc_separator - Model data: {'audio': {'chunk_size': 352800, 'dim_f': 1024, 'dim_t': 801, 'hop_length': 441, 'n_fft': 2048, 'num_channels': 2, 'sample_rate': 44100, 'min_mean_abs': 0.001}, 'model': {'dim': 512, 'depth': 12, 'stereo': True, 'num_stems': 1, 'time_transformer_depth': 1, 'freq_transformer_depth': 1, 'freqs_per_bands': (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 12, 12, 12, 12, 12, 12, 12, 12, 24, 24, 24, 24, 24, 24, 24, 24, 48, 48, 48, 48, 48, 48, 48, 48, 128, 129), 'dim_head': 64, 'heads': 8, 'attn_dropout': 0.1, 'ff_dropout': 0.1, 'flash_attn': True, 'dim_freqs_in': 1025, 'stft_n_fft': 2048, 'stft_hop_length': 441, 'stft_win_length': 2048, 'stft_normalized': False, 'mask_estimator_depth': 2, 'multi_stft_resolution_loss_weight': 1.0, 'multi_stft_resolutions_window_sizes': (4096, 2048, 1024, 512, 256), 'multi_stft_hop_size': 147, 'multi_stft_normalized': False}, 'training': {'batch_size': 16, 'gradient_accumulation_steps': 1, 'grad_clip': 0, 'instruments': ['Vocals', 'Instrumental'], 'lr': 5e-05, 'patience': 2, 'reduce_factor': 0.95, 'target_instrument': 'Vocals', 'num_epochs': 1000, 'num_steps': 1000, 'augmentation': False, 'augmentation_type': 'simple1', 'use_mp3_compress': False, 'augmentation_mix': True, 'augmentation_loudness': True, 'augmentation_loudness_type': 1, 'augmentation_loudness_min': 0.5, 'augmentation_loudness_max': 1.5, 'q': 0.95, 'coarse_loss_clip': True, 'ema_momentum': 0.999, 'optimizer': 'adam', 'other_fix': False, 'use_amp': True}, 'inference': {'batch_size': 1, 'dim_t': 801, 'num_overlap': 4}, 'is_roformer': True}
2024-07-03 01:26:54.576 - DEBUG - mdxc_separator - MDXC arch params: batch_size=1, segment_size=256, overlap=8
2024-07-03 01:26:54.576 - DEBUG - mdxc_separator - MDXC arch params: override_model_segment_size=False, pitch_shift=0
2024-07-03 01:26:54.576 - DEBUG - mdxc_separator - Loading checkpoint model for inference...
2024-07-03 01:26:54.577 - DEBUG - mdxc_separator - Loading Roformer model...
2024-07-03 01:26:54.577 - DEBUG - mdxc_separator - Loading BSRoformer model...
/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/functional.py:665: UserWarning: A window was not provided. A rectangular window will be applied,which is known to cause spectral leakage. Other windows such as torch.hann_window or torch.hamming_window can are recommended to reduce spectral leakage.To suppress this warning and use a rectangular window, explicitly set `window=torch.ones(n_fft, device=<device>)`. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/SpectralOps.cpp:842.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
2024-07-03 01:26:55.277 - DEBUG - mdxc_separator - is_vocal_main_target: True
2024-07-03 01:26:55.278 - INFO - mdxc_separator - MDXC Separator initialisation complete
2024-07-03 01:26:55.278 - DEBUG - separator - Loading model completed.
2024-07-03 01:26:55.278 - INFO - separator - Load model duration: 00:00:01
2024-07-03 01:26:55.278 - INFO - separator - Starting separation process for audio_file_path: tracks/prettier.mp3
2024-07-03 01:26:55.278 - DEBUG - separator - Normalization threshold set to 0.9, waveform will lowered to this max amplitude to avoid clipping.
2024-07-03 01:26:55.278 - DEBUG - mdxc_separator - Preparing mix for input audio file tracks/prettier.mp3...
2024-07-03 01:26:55.278 - DEBUG - common_separator - Loading audio from file: tracks/prettier.mp3
2024-07-03 01:26:55.637 - DEBUG - common_separator - Audio loaded. Sample rate: 44100, Audio shape: (2, 11344872)
2024-07-03 01:26:55.638 - DEBUG - common_separator - Audio file is valid and contains data.
2024-07-03 01:26:55.638 - DEBUG - common_separator - Mix preparation completed.
2024-07-03 01:26:55.638 - DEBUG - mdxc_separator - Normalizing mix before demixing...
2024-07-03 01:26:55.651 - DEBUG - mdxc_separator - Using model default segment size: 801
2024-07-03 01:26:55.651 - DEBUG - mdxc_separator - Number of stems: 1
2024-07-03 01:26:55.651 - DEBUG - mdxc_separator - Chunk size: 352800
2024-07-03 01:26:55.651 - DEBUG - mdxc_separator - Step: 352800
  0%|                                                                                                                                                      | 0/33 [00:00<?, ?it/s]/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/backends/cuda/__init__.py:342: FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
  warnings.warn(
  0%|                                                                                                                                                      | 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/andrew/miniforge3/envs/karaoke-prep/bin/audio-separator", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/utils/cli.py", line 177, in main
    output_files = separator.separate(args.audio_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/separator.py", line 704, in separate
    output_files = self.model_instance.separate(audio_file_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/architectures/mdxc_separator.py", line 134, in separate
    source = self.demix(mix=mix)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/architectures/mdxc_separator.py", line 248, in demix
    x = self.model_run(part.unsqueeze(0))[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/uvr_lib_v5/bs_roformer.py", line 508, in forward
    x = time_transformer(x).to(device)
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/karaoke-prep/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/uvr_lib_v5/bs_roformer.py", line 214, in forward
    x = attn(x) + x
        ~~~~~~~~^~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
```

Running the same command with the code on `main` has no issue and maxes out my macbook's GPU 👀

**Comment by young01ai** [comment]
Emmm... It's really strange. I test it locally on my macbook (M2) again just now, everything is ok on my machine. 

d06032b7-5e82-4dd1-9e78-c4a5b15926a3

**Comment by beveradb** [comment]
ah, you're testing using the mel_band roformer model which doesn't use the same code as the bs_roformer model - in this PR you've modified `audio_separator/separator/uvr_lib_v5/bs_roformer.py` but not https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/uvr_lib_v5/mel_band_roformer.py 😄

**Comment by young01ai** [comment]
Thx god, I finally done! @beveradb 
I found that there are two reasons why it's necessary to handle macos separately in (uvr5) reformer code:
1. scatter() not supported for complex on mps device
2. operator 'aten::unfold_backward' is not implemented for mps device, which seems effect torch.istft()
So, just solve them. I hope everything is ok now...

**Comment by beveradb** [comment]
Nice work! That's definitely working as it was before on my apple silicon mac now, for both mel and bs roformer models:

Monosnap 2024-07-03 10-17-05

Monosnap 2024-07-03 10-13-13

I've also tested with an A100 GPU on runpod:

image

So I can say with confidence that both roformer models now work with MPS and CUDA in `audio-separator` version `0.17.5` onwards - thank you again! 🙇

**Comment by young01ai** [comment]
@beveradb BTY, sdpa_flash kernel only supports float16 on sm80+ architecture gpu, temporarily, I just fix it by add 3 lines [here](https://github.com/karaokenerds/python-audio-separator/blob/f2b78ef389ff8d50cde384b52a5a0bddf702ef62/audio_separator/separator/uvr_lib_v5/attend.py#L73-L75) in this PR.

**Pull request merged**
