### PR TITLE
Add support for MDXC models

### PR DESCRIPTION
**Pull request by zhzhongshi**

### CODE REVIEW

**Comment by zhzhongshi** [comment]
just for MDX23C-8KFFT-InstVoc_HQ.ckpt :(

**Comment by beveradb** [comment]
Amazing, thank you so much!! 🚀 

I'll give this a test shortly and assuming all works well, will merge and release a new version! 🙇

**Comment by beveradb** [comment]
Hey @zhzhongshi I tried to get this working this evening but wasn't able to.
I first had some issues with the model data YAML file not being downloaded correctly (which was my own code and my own bug so I've fixed that and pushed my commits).

However, the error I'm getting now (`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`) seems to be relating to how the checkpoint model is being loaded, and I think you might have more of an idea of what's supposed to be happening here?

Here's my log output, maybe you know what the issue is?
If not, I'll dig into this tomorrow and try and finish off this PR / get it all working.


```

audio-separator -d --model_filename MDX23C-8KFFT-InstVoc_HQ.ckpt tracks/test.wav
2024-03-13 22:30:04.918 - INFO - cli - Separator version 0.16.0 beginning with input file: tracks/test.wav
2024-03-13 22:30:06.380 - INFO - separator - Separator version 0.16.0 instantiating with output_dir: None, output_format: FLAC
2024-03-13 22:30:06.380 - INFO - separator - Operating System: Darwin Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:10 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6031
2024-03-13 22:30:06.380 - INFO - separator - System: Darwin Node: MacBook-Pro-2.local Release: 23.3.0 Machine: arm64 Proc: arm
2024-03-13 22:30:06.380 - INFO - separator - Python Version: 3.11.7
2024-03-13 22:30:06.380 - INFO - separator - PyTorch Version: 2.2.1
2024-03-13 22:30:06.544 - INFO - separator - FFmpeg installed: ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
2024-03-13 22:30:06.545 - DEBUG - separator - Python package: onnxruntime-gpu not installed
2024-03-13 22:30:06.546 - DEBUG - separator - Python package: onnxruntime-silicon not installed
2024-03-13 22:30:06.546 - INFO - separator - ONNX Runtime CPU package installed with version: 1.17.1
2024-03-13 22:30:06.560 - INFO - separator - Apple Silicon MPS/CoreML is available in Torch, setting Torch device to MPS
2024-03-13 22:30:06.560 - INFO - separator - ONNXruntime has CoreMLExecutionProvider available, enabling acceleration
2024-03-13 22:30:06.560 - INFO - separator - Loading model MDX23C-8KFFT-InstVoc_HQ.ckpt...
2024-03-13 22:30:06.560 - DEBUG - separator - File already exists at /tmp/audio-separator-models/download_checks.json, skipping download
2024-03-13 22:30:06.561 - DEBUG - separator - Model download list loaded
2024-03-13 22:30:06.561 - DEBUG - separator - Searching for model_filename MDX23C-8KFFT-InstVoc_HQ.ckpt in supported_model_files_grouped
2024-03-13 22:30:06.561 - DEBUG - separator - Found input filename MDX23C-8KFFT-InstVoc_HQ.ckpt in multi-file model: MDX23C Model: MDX23C-InstVoc HQ
2024-03-13 22:30:06.561 - DEBUG - separator - Multi-file model identified: MDX23C Model: MDX23C-InstVoc HQ, iterating through files to download
2024-03-13 22:30:06.561 - DEBUG - separator - Attempting to identify download URL for config pair: MDX23C-8KFFT-InstVoc_HQ.ckpt -> model_2_stem_full_band_8k.yaml
2024-03-13 22:30:06.561 - DEBUG - separator - File already exists at /tmp/audio-separator-models/MDX23C-8KFFT-InstVoc_HQ.ckpt, skipping download
2024-03-13 22:30:06.561 - DEBUG - separator - All files downloaded for model MDX23C Model: MDX23C-InstVoc HQ, returning initial path /tmp/audio-separator-models/MDX23C-8KFFT-InstVoc_HQ.ckpt
2024-03-13 22:30:06.561 - DEBUG - separator - Model downloaded, friendly name: MDX23C Model: MDX23C-InstVoc HQ
2024-03-13 22:30:06.561 - DEBUG - separator - Calculating MD5 hash for model file to identify model parameters from UVR data...
2024-03-13 22:30:06.561 - DEBUG - separator - Calculating hash of model file /tmp/audio-separator-models/MDX23C-8KFFT-InstVoc_HQ.ckpt
2024-03-13 22:30:06.583 - DEBUG - separator - Model /tmp/audio-separator-models/MDX23C-8KFFT-InstVoc_HQ.ckpt has hash 6682b2dbf51e64c9ea5ef811f007190e
2024-03-13 22:30:06.583 - DEBUG - separator - VR model data path set to /tmp/audio-separator-models/vr_model_data.json
2024-03-13 22:30:06.583 - DEBUG - separator - File already exists at /tmp/audio-separator-models/vr_model_data.json, skipping download
2024-03-13 22:30:06.583 - DEBUG - separator - MDX model data path set to /tmp/audio-separator-models/mdx_model_data.json
2024-03-13 22:30:06.583 - DEBUG - separator - File already exists at /tmp/audio-separator-models/mdx_model_data.json, skipping download
2024-03-13 22:30:06.583 - DEBUG - separator - Loading MDX and VR model parameters from UVR model data files...
2024-03-13 22:30:06.584 - DEBUG - separator - MDXC model data path set to /tmp/audio-separator-models/model_2_stem_full_band_8k.yaml
2024-03-13 22:30:06.584 - DEBUG - separator - File already exists at /tmp/audio-separator-models/model_2_stem_full_band_8k.yaml, skipping download
2024-03-13 22:30:06.587 - DEBUG - separator - Model data loaded from YAML file: {'audio': {'chunk_size': 261120, 'dim_f': 4096, 'dim_t': 256, 'hop_length': 1024, 'n_fft': 8192, 'num_channels': 2, 'sample_rate': 44100, 'min_mean_abs': 0.001}, 'model': {'act': 'gelu', 'bottleneck_factor': 4, 'growth': 128, 'norm': 'InstanceNorm', 'num_blocks_per_scale': 2, 'num_channels': 128, 'num_scales': 5, 'num_subbands': 4, 'scale': [2, 2]}, 'training': {'batch_size': 6, 'grad_clip': 0, 'instruments': ['Vocals', 'Instrumental'], 'lr': 1e-05, 'patience': 2, 'reduce_factor': 0.95, 'target_instrument': None, 'num_epochs': 1000, 'num_steps': 1000, 'augmentation': 1, 'augmentation_type': 'simple1', 'augmentation_mix': True, 'q': 0.95, 'coarse_loss_clip': True, 'ema_momentum': 0.999}, 'inference': {'batch_size': 1, 'dim_t': 256, 'num_overlap': 8}}
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: model_name=MDX23C-8KFFT-InstVoc_HQ, model_path=/tmp/audio-separator-models/MDX23C-8KFFT-InstVoc_HQ.ckpt
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: primary_stem_output_path=None, secondary_stem_output_path=None
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: output_dir=None, output_format=FLAC
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: normalization_threshold=0.9
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: enable_denoise=None, output_single_stem=None
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: invert_using_spec=False, sample_rate=44100
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: primary_stem_name=Vocals, secondary_stem_name=Instrumental
2024-03-13 22:30:07.388 - DEBUG - common_separator - Common params: is_karaoke=False, is_bv_model=False, bv_model_rebalance=0
2024-03-13 22:30:07.388 - DEBUG - mdxc_separator - MDXC arch params: batch_size=1, segment_size=256, overlap=8
2024-03-13 22:30:07.388 - DEBUG - mdxc_separator - Loading Checkpoint model for inference...
Traceback (most recent call last):
  File "/Users/andrew/miniforge3/envs/audio-separator-dev/bin/audio-separator", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/utils/cli.py", line 165, in main
    separator.load_model(model_filename=args.model_filename)
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/separator.py", line 618, in load_model
    self.model_instance = separator_class(common_config=common_params, arch_config=self.arch_specific_params[model_type])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/architectures/mdxc_separator.py", line 33, in __init__
    self.load_model(common_config)
  File "/Users/andrew/Projects/python-audio-separator/audio_separator/separator/architectures/mdxc_separator.py", line 48, in load_model
    model.load_state_dict(torch.load(model_path, map_location="cpu"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/audio-separator-dev/lib/python3.11/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/miniforge3/envs/audio-separator-dev/lib/python3.11/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

```

**Comment by zhzhongshi** [comment]
I can't reproduce the issue, I tried windows python3.10 and ubuntu 22.04 python3.10, both works

**Comment by beveradb** [comment]
Hey @zhzhongshi ,

I figured it out in the end - my model file (`MDX23C-8KFFT-InstVoc_HQ.ckpt`) had not downloaded fully, so there was a file in right place but it wasn't actually a valid file!
So, I added error handling for that case, re-downloaded the file and was able to get it to work!

I've then pushed a bunch more commits today tidying this up a bit more, bringing it in line with the code style of the rest of the `audio-separator` project with more descriptive variable names and log entries, refactoring to make sure I myself understand what's going on at each stage etc.

I also added the other config params and tidied up the CLI args a bit too, fixed the pitch fix implementation and tested that.

Hope that's all ok - I'm going to merge this now, so `audio-separator` version `0.16.0` and above will finally support MDXC (at least, the `MDX23C-8KFFT-InstVoc_HQ.ckpt` model as that's all I've tested so far).

Thanks so much for doing the initial work on this, I really appreciate it! 🙇

**Pull request merged**
